[tool.poetry]
name = "governanceplatform"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
psycopg2-binary = "^2.8.4"
cryptography = "^39.0.1"
django-cors-headers = "^3.14.0"
drf-spectacular = "^0.26.1"
drf-spectacular-sidecar = "^2023.4.1"
django-bootstrap-v5 = "^1.0.11"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
