# Generated by Django 4.2 on 2023-07-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nisinp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Question Category', 'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterModelOptions(
            name='questioncategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Question Category Translation'},
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nisinp.questioncategory'),
        ),
    ]
