# Generated by Django 4.2.7 on 2024-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0003_alter_knowledge_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcetranslation",
            name="path",
            field=models.FilePathField(
                max_length=200,
                path="/home/cases/eLearning/theme/static/media",
                recursive=True,
            ),
        ),
    ]
