# Generated by Django 4.2.7 on 2024-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0004_alter_resourcetranslation_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextresourcetemplate",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contexttexttemplate",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
