# Generated by Django 4.2.4 on 2023-09-12 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0004_alter_resourcetranslation_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leveltranslation",
            old_name="objectives",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="level",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="level",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="leveltranslation",
            name="plot",
        ),
        migrations.RemoveField(
            model_name="leveltranslation",
            name="requirements",
        ),
    ]
