# Generated by Django 4.2.7 on 2024-04-04 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0005_alter_contextresourcetemplate_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="score",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
