# Generated by Django 4.2.7 on 2024-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0006_score_created_at_score_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
