# Generated by Django 4.2.6 on 2023-10-30 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0010_alter_levelsequence_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
