# Generated by Django 4.2.6 on 2023-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0011_alter_score_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
