# Generated by Django 4.2.6 on 2023-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0013_alter_knowledge_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status_level",
        ),
    ]
