# Generated by Django 4.2.6 on 2023-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0015_levelsequence_elearning_l_content_014797_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.RemoveField(
            model_name="context",
            name="index",
        ),
        migrations.RemoveField(
            model_name="context",
            name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.RemoveField(
            model_name="question",
            name="index",
        ),
        migrations.RemoveField(
            model_name="question",
            name="level",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="category",
        ),
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(to="elearning.category"),
        ),
    ]
