# Generated by Django 4.2.6 on 2023-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0018_remove_user_current_question_user_current_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledge",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
