# Generated by Django 4.2.7 on 2023-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0019_alter_knowledge_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengetranslation",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="challengetranslation",
            name="name",
            field=models.TextField(),
        ),
    ]
