# Generated by Django 4.2.7 on 2023-11-09 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0020_challengetranslation_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextmediatemplate",
            name="css_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contexttexttemplate",
            name="css_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
