# Generated by Django 4.2.7 on 2023-11-15 08:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0022_alter_contextmediatemplate_css_classes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerChoiceCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer choice category",
                "verbose_name_plural": "Answer choice categories",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="answer_text",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="path",
            field=models.FilePathField(
                path="C:\\Users\\alexis\\Documents\\CYBERLUX Projects\\eLearning\\theme/static/",
                recursive=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="q_type",
            field=models.CharField(
                choices=[
                    ("M", "Multiple Choice"),
                    ("S", "Single Choice"),
                    ("SO", "Single Option Choice"),
                    ("T", "Free text"),
                    ("MT", "Multiple Choice + Free Text"),
                    ("ST", "Single Choice + Free Text"),
                    ("CL", "Countries list"),
                    ("CA", "Categorisation"),
                    ("SR", "Sorting"),
                    ("LI", "Linking"),
                ],
                default="M",
                max_length=2,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="path",
            field=models.FilePathField(
                path="C:\\Users\\alexis\\Documents\\CYBERLUX Projects\\eLearning\\theme/static/",
                recursive=True,
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="answer_choice_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning.answerchoicecategory",
            ),
        ),
        migrations.CreateModel(
            name="AnswerChoiceCategoryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="label")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="elearning.answerchoicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer choice category Translation",
                "db_table": "elearning_answerchoicecategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
