# Generated by Django 4.2.7 on 2023-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0024_alter_answerchoice_answer_choice_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontranslation",
            name="explanation",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
