# Generated by Django 4.2.7 on 2023-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0025_alter_questiontranslation_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="elearning.category"
            ),
        ),
    ]
