# Generated by Django 4.2.7 on 2024-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0027_alter_question_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledge",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
