# Generated by Django 4.2.7 on 2024-01-23 08:11

import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0028_alter_knowledge_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation",
                "verbose_name_plural": "Explanations",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="questiontranslation",
            name="explanation",
        ),
        migrations.CreateModel(
            name="ExplanationTextTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("TL", "Top Left"),
                            ("TC", "Top Center"),
                            ("TR", "Top Right"),
                            ("ML", "Middle Left"),
                            ("MC", "Middle Center"),
                            ("MR", "Middle Right"),
                            ("BL", "Bottom Left"),
                            ("BC", "Bottom Center"),
                            ("BR", "Bottom Right "),
                        ],
                        default="TL",
                        max_length=2,
                    ),
                ),
                (
                    "css_classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.explanation",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elearning.text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Template",
                "verbose_name_plural": "Text Templates",
            },
        ),
        migrations.CreateModel(
            name="ExplanationMediaTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("TL", "Top Left"),
                            ("TC", "Top Center"),
                            ("TR", "Top Right"),
                            ("ML", "Middle Left"),
                            ("MC", "Middle Center"),
                            ("MR", "Middle Right"),
                            ("BL", "Bottom Left"),
                            ("BC", "Bottom Center"),
                            ("BR", "Bottom Right "),
                        ],
                        default="TL",
                        max_length=2,
                    ),
                ),
                (
                    "css_classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.explanation",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Template",
                "verbose_name_plural": "Media Templates",
            },
        ),
        migrations.AddField(
            model_name="explanation",
            name="medias",
            field=models.ManyToManyField(
                through="elearning.ExplanationMediaTemplate", to="elearning.media"
            ),
        ),
        migrations.AddField(
            model_name="explanation",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elearning.question",
            ),
        ),
        migrations.AddField(
            model_name="explanation",
            name="texts",
            field=models.ManyToManyField(
                through="elearning.ExplanationTextTemplate", to="elearning.text"
            ),
        ),
        migrations.CreateModel(
            name="ExplanationTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.TextField(verbose_name="Label")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="elearning.explanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation Translation",
                "db_table": "elearning_explanation_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
