# Generated by Django 4.2.7 on 2024-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elearning",
            "0029_explanation_remove_questiontranslation_explanation_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answerchoicecategorytranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="answerchoicecategorytranslation",
            name="master",
        ),
        migrations.RemoveField(
            model_name="answerchoice",
            name="answer_choice_category",
        ),
        migrations.RemoveField(
            model_name="answerchoice",
            name="answer_text",
        ),
        migrations.AddField(
            model_name="contexttexttemplate",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contextmediatemplate",
            name="position",
            field=models.CharField(
                choices=[
                    ("NA", "Not applicable"),
                    ("TL", "Top Left"),
                    ("TC", "Top Center"),
                    ("TR", "Top Right"),
                    ("ML", "Middle Left"),
                    ("MC", "Middle Center"),
                    ("MR", "Middle Right"),
                    ("BL", "Bottom Left"),
                    ("BC", "Bottom Center"),
                    ("BR", "Bottom Right "),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="contexttexttemplate",
            name="position",
            field=models.CharField(
                choices=[
                    ("NA", "Not applicable"),
                    ("TL", "Top Left"),
                    ("TC", "Top Center"),
                    ("TR", "Top Right"),
                    ("ML", "Middle Left"),
                    ("MC", "Middle Center"),
                    ("MR", "Middle Right"),
                    ("BL", "Bottom Left"),
                    ("BC", "Bottom Center"),
                    ("BR", "Bottom Right "),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="explanationmediatemplate",
            name="position",
            field=models.CharField(
                choices=[
                    ("NA", "Not applicable"),
                    ("TL", "Top Left"),
                    ("TC", "Top Center"),
                    ("TR", "Top Right"),
                    ("ML", "Middle Left"),
                    ("MC", "Middle Center"),
                    ("MR", "Middle Right"),
                    ("BL", "Bottom Left"),
                    ("BC", "Bottom Center"),
                    ("BR", "Bottom Right "),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="explanationtexttemplate",
            name="position",
            field=models.CharField(
                choices=[
                    ("NA", "Not applicable"),
                    ("TL", "Top Left"),
                    ("TC", "Top Center"),
                    ("TR", "Top Right"),
                    ("ML", "Middle Left"),
                    ("MC", "Middle Center"),
                    ("MR", "Middle Right"),
                    ("BL", "Bottom Left"),
                    ("BC", "Bottom Center"),
                    ("BR", "Bottom Right "),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="questionmediatemplate",
            name="position",
            field=models.CharField(
                choices=[
                    ("NA", "Not applicable"),
                    ("TL", "Top Left"),
                    ("TC", "Top Center"),
                    ("TR", "Top Right"),
                    ("ML", "Middle Left"),
                    ("MC", "Middle Center"),
                    ("MR", "Middle Right"),
                    ("BL", "Bottom Left"),
                    ("BC", "Bottom Center"),
                    ("BR", "Bottom Right "),
                ],
                default="NA",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="AnswerChoiceCategory",
        ),
        migrations.DeleteModel(
            name="AnswerChoiceCategoryTranslation",
        ),
    ]
