# Generated by Django 4.2.7 on 2024-01-29 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elearning",
            "0030_alter_answerchoicecategorytranslation_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
