# Generated by Django 4.2.7 on 2024-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0032_quiz_quizquestion_quiz_questions_quiztranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="display_quiz_label",
            field=models.BooleanField(
                default=True, verbose_name="Do display the label quiz ?"
            ),
        ),
    ]
