# Generated by Django 4.2.7 on 2024-02-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0033_quizquestion_display_quiz_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="display_quiz_label",
            field=models.BooleanField(default=True, verbose_name="Display label quiz?"),
        ),
        migrations.CreateModel(
            name="QuestionAnswerChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Is it the correct answer ?"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "answerChoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.answerchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Answer Choice",
                "verbose_name_plural": "Question Answer Choices",
            },
        ),
    ]
