# Generated by Django 4.2.7 on 2024-02-13 08:04

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Question = apps.get_model("elearning", "Question")
    QuestionAnswerChoice = apps.get_model("elearning", "QuestionAnswerChoice")
    for question in Question.objects.all():
        for answer_choice in question.answer_choices.all():
            QuestionAnswerChoice(
                answerChoice=answer_choice,
                question=question,
                index=answer_choice.index,
                is_correct=answer_choice.is_correct,
                score=answer_choice.score,
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0034_alter_quizquestion_display_quiz_label_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_through_relations, reverse_code=migrations.RunPython.noop
        ),
    ]
