# Generated by Django 4.2.7 on 2024-02-13 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0035_auto_20240213_0804"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer_choices",
        ),
    ]
