# Generated by Django 4.2.7 on 2024-02-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0036_remove_question_answer_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_choices",
            field=models.ManyToManyField(
                through="elearning.QuestionAnswerChoice", to="elearning.answerchoice"
            ),
        ),
    ]
