# Generated by Django 4.2.7 on 2024-02-13 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0037_question_answer_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerchoice",
            name="index",
        ),
        migrations.RemoveField(
            model_name="answerchoice",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="answerchoice",
            name="score",
        ),
    ]
