# Generated by Django 4.2.7 on 2024-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0038_remove_answerchoice_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="index",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
