# Generated by Django 4.2.7 on 2024-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0039_alter_quizquestion_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerchoice",
            name="index",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
