# Generated by Django 4.2.7 on 2024-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0041_alter_questionanswerchoice_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswerchoice",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
