# Generated by Django 4.2.7 on 2024-02-21 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0042_alter_questionanswerchoice_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="categories",
        ),
    ]
