# Generated by Django 4.2.7 on 2024-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0043_remove_quiz_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text",
            name="hyperlink",
        ),
        migrations.AddField(
            model_name="texttranslation",
            name="hyperlink",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
