# Generated by Django 4.2.7 on 2024-02-22 08:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0044_remove_text_hyperlink_texttranslation_hyperlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="path",
        ),
        migrations.AddField(
            model_name="resourcetranslation",
            name="path",
            field=models.FilePathField(
                default=" ",
                path="/home/cases/eLearning/theme/static/media",
                recursive=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ContextResourceTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("NA", "Not applicable"),
                            ("TL", "Top Left"),
                            ("TC", "Top Center"),
                            ("TR", "Top Right"),
                            ("ML", "Middle Left"),
                            ("MC", "Middle Center"),
                            ("MR", "Middle Right"),
                            ("BL", "Bottom Left"),
                            ("BC", "Bottom Center"),
                            ("BR", "Bottom Right "),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "css_classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.context",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Template",
                "verbose_name_plural": "Resource Templates",
            },
        ),
        migrations.AddField(
            model_name="context",
            name="resources",
            field=models.ManyToManyField(
                through="elearning.ContextResourceTemplate", to="elearning.resource"
            ),
        ),
    ]
