# Generated by Django 4.2.7 on 2024-02-22 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0045_remove_resource_path_resourcetranslation_path_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challengetranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="challengetranslation",
            name="master",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="ChallengeTranslation",
        ),
    ]
