# Generated by Django 4.2.7 on 2024-02-29 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0046_alter_challengetranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="questionanswerchoice",
            name="score",
        ),
    ]
